### ISSUE TITLE
Speed Issue

### ISSUE THREAD

**Issue by usherfiles** [JonathanxD/JsBlobDownloader#2]
Hi jonathan, it's me again :) First I want to thank you for your efford on the development of this script, it works flawlessly and it can be the best solution for people like me that works on a shared host with a limited use of php.
However I've been trying of make it work at full speed during the download but it's impossible, The problem is that I don't know if it's my host limiting the download rate after downloading with your script, or your script is limiting itself, or another thing. I tried Google Chrome and Microsoft Edge and both does the same.
Downloading from the direct link (download.php) does download fine  but it get cut out because the php timeout after 4 minutes.
Downloading with your script works fine at full speed for like 1 minute, after that, the download speed is limited exactly at 99kb/s till the download ends.
I've tried with direct link .exe files, php files, zip files and all them does the same.
I'll put a capture on the issue of the element inspector that reflects what I'm talking about.
Can you test if it's your script or my host? I don't have the knowledge to read all your script (I know javascript but not THAT much as you)
Here's the link for the test : https://edmcentralargentina.com/asdfg/?member=JonathanxD
The file is just a 512 MB file of random data, the data doesn't matter, the problem here is the download rate haha, check the  attached image here: 
![captura](https://user-images.githubusercontent.com/8587998/38074840-9de0258e-3306-11e8-85e6-922288adee3f.PNG)

**Comment by jhrldev** [comment]
I'm getting a 404 (and 500) status code, but I have a [test website](http://jsu.zz.mu/jsblobdownloader) and I haven't experienced this issue (I have a slow internet). See the result of 6.8MB mp3 download:

![MP3](https://cdn.pbrd.co/images/HjQqYFD.png)

These variations is because of bandwidth usage of other devices.

Then I tried something more hard, I've enabled throttling, but I was not able to reproduce the issue (I've ended up with constant 10s download time), I think that it is limitation of your host, but I need more testing to end with something more concrete. Maybe on the next weekend I investigate this deeper, also I've some improvements to do to script.

**Comment by jhrldev** [comment]
Sorry for the F*KING LONG DELAY. I'm a little busy now and I've recently changed my Internet plan, so I was able to test it more precisely and I concluded that it is not a problem with the script, its more probable to be a problem with the host, possibly slowing down speed of subsequent connections (AFAIK the Xhr close the connection after download finishes, so it is not a limit imposed based on amount of connections). 

If you still think that the problem is with the script I will be happy to fix the problem, simply open a new issue, and if possible, explain how to reproduce the problem (if you don't know how, simply say which host service do you use, I'll create a site and test it out :D).
